### ISSUE TITLE
compiling with sudo is usually not a good idea

### ISSUE THREAD

**Issue by samoht** [talex5/mirage-trace-viewer#5]
Is there a way for:

```
mirage-trace-viewer -d <domain> --html=<dir>`
```

To not run `make` in the `dir` directory? I'd rather run `make` myself to control what's in the environment (as it fails on my machine, as `root` doesn't have OPAM installed).

**Comment by talex5** [comment]
Use `-w -` to pipe into a non-sudo process?

**Comment by talex5** [comment]
Assuming the work-around is OK and closing...
