### ISSUE TITLE
What's the best way to expose traces for a virtualbox image

### ISSUE THREAD

**Issue by samoht** [talex5/mirage-trace-viewer#6]
I'm running the profiler inside xen inside a virtualbox on a mac. What's the best way to see the traces (there's no browser inside my vagrant image for html and not gtk). Can I just copy the `.bin` file over?

**Comment by talex5** [comment]
You can copy the `.ctf` file, yes. Or:

    ssh root@vagrantvm mirage-trace-viewer -d mydom -w - | mirage-trace-viewer -

More details are at <http://openmirage.org/wiki/profiling>.

**Comment by samoht** [comment]
ha sorry, I've read that page but it seems I have overlooked that bit. Thanks!
