### ISSUE TITLE
Problem with 0install binary

### ISSUE THREAD

**Issue by MagnusS** [talex5/mirage-trace-viewer#7]
I installed mirage-trace-viewer with 0install in Ubuntu 14.04, but I am unable to view the traces in HTML or with the GTK plugin. I'm probably missing some dependencies, but I'm not sure which libraries to install...

GTK error:

``` bash
$ mirage-trace-viewer trace.ctf
mirage-trace-viewer: GTK plugin failed: GtkMain.init: initialization
                     failed
                     ml_gtk_init: initialization failed
                     Hint: try --html=dir instead
```

HTML error:

``` bash
$ mirage-trace-viewer trace.ctf  --html=.
make -C .
make: Entering directory `/home/mag/git/mirage-tcpip/trace'
ocamlbuild -use-ocamlfind loader.byte
+ ocamlfind ocamldep -package mirage-trace-viewer.js -modules loader.ml > loader.ml.depends
ocamlfind: Package `mirage-trace-viewer.js' not found
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
make: *** [all] Error 10
make: Leaving directory `/home/mag/git/mirage-tcpip/trace'
mirage-trace-viewer: Child returned error exit status 2
```

**Comment by MagnusS** [comment]
I installed various gtk libraries and gtk works fine now. I'm using it over ssh and X11 forwarding turned out to be disabled in my tmux session, so could have been related to that as well... Disabling forwarding gives the same error.

`--html` still doesn't work though.

**Comment by talex5** [comment]
Hmm, yes `--html` creates a directory which you have to compile, and so requires a build environment. Not sure much can be done about that...

**Comment by MagnusS** [comment]
Aha - ok thanks. After clone/install from source `--html` works.

**Comment by talex5** [comment]
I've converted it to dune, with separate packages, so installing from source should be easier now.
